<div class="slides">
<ul id="slider">
<li>
<a href="https://nichinare.com/request/form.cgi" ><img src="/common/slider/pc_191101.jpg" alt="" /></a></li>
<li>
<a href="https://nichinare.com/course/start_up_course.html" ><img src="/common/slider/pc_2.jpg" alt="" /></a></li>
<li>
<a href="https://nichinare.com/course/workshop.html" ><img src="/common/slider/pc_3.jpg" alt="" /></a></li>
<li>
<img src="/common/slider/p4.jpg" alt="" />
</li>
<li>
<img src="/common/slider/p5.jpg" alt="" />
</li>
<li>
<img src="/common/slider/p6.jpg" alt="" />
</li>
<li>
<img src="/common/slider/p7.jpg" alt="" />
</li>
</ul>
</div>
