<nav class="anime_bnr">
<ul>
<li><a href="http://maerchen-anime.com/" target="_blank" rel="nofollow" onclick="ga('send', 'event', 'link', 'click', 'sp_maerchen', 1);"><img src="/common/bnr/maerchen.jpg" width="145" height="45" alt="メルヘン・メドヘン" /></a></li>
<li><a href="http://centaur-anime.com/" target="_blank" rel="nofollow" onclick="ga('send', 'event', 'link', 'click', 'sp_centaur', 1);"><img src="/common/bnr/centaur_banner.jpg" width="145" height="45" alt="セントールの悩み" /></a></li>
<li><a href="http://www.tbs.co.jp/anime/cp/" target="_blank" rel="nofollow" onclick="ga('send', 'event', 'link', 'click', 'sp_clockwork_planet', 1);"><img src="/common/bnr/clockwork_planet.jpg" width="145" height="45" alt="クロックワークプラネット" /></a></li>
<li><a href="http://www.tbs.co.jp/anime/gn/" target="_blank" rel="nofollow" onclick="ga('send', 'event', 'link', 'click', 'sp_gaanime', 1);"><img src="/common/bnr/gn.jpg" width="145" height="45" alt="ガーリッシュ ナンバー" /></a></li>
<li><a href="http://keijollllllll.com/" target="_blank" rel="nofollow" onclick="ga('send', 'event', 'link', 'click', 'sp_keijo', 1);"><img src="/common/bnr/keijo.jpg" width="145" height="45" alt="競女" /></a></li>
<li><a href="http://www.tbs.co.jp/anime/handaanime/" target="_blank" rel="nofollow" onclick="ga('send', 'event', 'link', 'click', 'sp_handaanime', 1);"><img src="/common/bnr/handakun.jpg" width="145" height="45" alt="はんだくん" /></a></li>
<li><a href="http://mononokean.tv/" target="_blank" rel="nofollow" onclick="ga('send', 'event', 'link', 'click', 'sp_monoanime', 1);"><img src="/common/bnr/mono.jpg" width="145" height="45" alt="不機嫌なモノノケ庵" /></a></li>
<li><a href="http://www.tbs.co.jp/anime/sakamoto/" target="_blank" rel="nofollow" onclick="ga('send', 'event', 'link', 'click', 'sp_sakamoto', 1);"><img src="/common/bnr/sakamotodesuga_banner.jpg" width="145" height="45" alt="坂本ですが？" /></a></li>
<li><a href="http://www.tbs.co.jp/anime/meido/" target="_blank" rel="nofollow" onclick="ga('send', 'event', 'link', 'click', 'sp_meido', 1);"><img src="/common/bnr/syounenmaid_banner.jpg" width="145" height="45" alt="少年メイド" /></a></li>
<li><a href="http://www.tbs.co.jp/anime/lance/" target="_blank" rel="nofollow" onclick="ga('send', 'event', 'link', 'click', 'sp_lance', 1);"><img src="/common/bnr/lance.jpg" width="145" height="45" alt="ランス・アンド・マスクス" /></a></li>
<li><a href="http://monmusu.tv/" target="_blank" rel="nofollow" onclick="ga('send', 'event', 'link', 'click', 'sp_monmusu', 1);"><img src="/common/bnr/monmusu.jpg" width="145" height="45" alt="モンスター娘のいる日常" /></a></li>
<li><a href="http://www.tbs.co.jp/anime/aoharu/" target="_blank" rel="nofollow" onclick="ga('send', 'event', 'link', 'click', 'sp_aoharu', 1);"><img src="/common/bnr/aoharu.jpg" width="145" height="45" alt="青春×機関銃" /></a></li>
<li><a href="http://www.tbs.co.jp/anime/fafnir/" target="_blank" rel="nofollow" onclick="ga('send', 'event', 'link', 'click', 'sp_fafnir', 1);"><img src="/common/bnr/faf_banner.jpg" width="145" height="45" alt="ファフニール" /></a></li>
<li><a href="http://www.vap.co.jp/ookamishojo-anime/" target="_blank" rel="nofollow" onclick="ga('send', 'event', 'link', 'click', 'sp_ookami', 1);"><img src="/common/bnr/ookami_banner.jpg" width="145" height="45" alt="オオカミ少女と黒王子" /></a></li>
<li><a href="http://sabagebu.com/" target="_blank" rel="nofollow" onclick="ga('send', 'event', 'link', 'click', 'sp_sabage', 1);"><img src="/common/bnr/savage_banner.jpg" width="145" height="45" alt="さばげぶっ！" /></a></li>
<li><a href="http://www.vap.co.jp/jinsei/" target="_blank" rel="nofollow" onclick="ga('send', 'event', 'link', 'click', 'sp_jinsei', 1);"><img src="/common/bnr/jinsei_banner.jpg" width="145" height="45" alt="人生" /></a></li>
<li><a href="http://www.vap.co.jp/gokukoku/" target="_blank" rel="nofollow" onclick="ga('send', 'event', 'link', 'click', 'sp_gokukoku', 1);"><img src="/common/bnr/brynhildr_banner.jpg" width="145" height="45" alt="極黒のブリュンヒルデ" /></a></li>
<li><a href="http://www.akuma-riddle.com/" target="_blank" rel="nofollow" onclick="ga('send', 'event', 'link', 'click', 'sp_riddle', 1);"><img src="/common/bnr/akuma_banner.jpg" width="145" height="45" alt="悪魔のリドル" /></a></li>
<li><a href="http://www.vap.co.jp/nobunagun/" target="_blank" rel="nofollow" onclick="ga('send', 'event', 'link', 'click', 'sp_nobu', 1);"><img src="/common/bnr/nobunagun_banner.jpg" width="145" height="45" alt="ノブナガン" /></a></li>
<li><a href="http://nichinare.com/error/post.html" target="_blank" rel="nofollow" onclick="ga('send', 'event', 'link', 'click', 'sp_koiuta', 1);"><img src="/common/bnr/koiuta_banner.jpg" width="145" height="45" alt="とある飛空士への恋歌" /></a></li>
<li><a href="http://watamote.jp/" target="_blank" rel="nofollow" onclick="ga('send', 'event', 'link', 'click', 'sp_watamote', 1);"><img src="/common/bnr/watamote_banner.jpg" width="145" height="45" alt="私がモテないのはどう考えてもお前らが悪い！" /></a></li>
<li><a href="http://arata-anime.com/" target="_blank" rel="nofollow" onclick="ga('send', 'event', 'link', 'click', 'sp_arata', 1);"><img src="/common/bnr/arata_banner.jpg" width="145" height="45" alt="『アラタカンガタリ 革神語』アニメ スペシャルサイト" /></a></li>
<li><a href="http://nichinare.com/error/post.html" target="_blank" rel="nofollow" onclick="ga('send', 'event', 'link', 'click', 'sp_anibun', 1);"><img src="/common/bnr/anibun_banner.jpg" width="145" height="45" alt="あにぶん" /></a></li>
</ul>
</nav>
