<div class="slides_container">
<p>
<a href="https://nichinare.com/news/2019/07/0704-349.html" ><img src="/sp/common/slider/sp_190704.jpg" width="305" height="171" alt=""></a></p>
<p>
<a href="http://nichinare.com/course/start_up_course.html" ><img src="/sp/common/slider/sp_2.jpg" width="305" height="171" alt=""></a></p>
<p>
<a href="http://nichinare.com/course/jr.html" ><img src="/sp/common/slider/sp_img03.jpg" width="305" height="171" alt=""></a></p>
<p>
<img src="/sp/common/slider/photo03.jpg" width="305" height="171" alt="">
</p>
<p>
<img src="/sp/common/slider/photo04.jpg" width="305" height="171" alt="">
</p>
<p>
<img src="/sp/common/slider/photo05.jpg" width="305" height="171" alt="">
</p>
<p>
<img src="/sp/common/slider/photo06.jpg" width="305" height="171" alt="">
</p>
</div>
