<div id="new_pager" class="clearfix">
<a data-slide-index="0" href="" ><img src="/common/slider/s01.jpg" alt="" /></a>
<a data-slide-index="1" href="" ><img src="/common/slider/s02.jpg" alt="" /></a>
<a data-slide-index="2" href="" ><img src="/common/slider/s03.jpg" alt="" /></a>
<a data-slide-index="3" href="" ><img src="/common/slider/s04.jpg" alt="" /></a>
<a data-slide-index="4" href="" ><img src="/common/slider/s05.jpg" alt="" /></a>
<a data-slide-index="5" href="" ><img src="/common/slider/s06.jpg" alt="" /></a>
<a data-slide-index="6" href="" ><img src="/common/slider/s07.jpg" alt="" /></a>
</div>
